secrets:
    DB_USER: ENC[AES256_GCM,data:GQM0OA==,iv:B8r1pTOdj8kTwcfCbpQbHgwanSOX7ceUtJ1lO2bhCOA=,tag:CwWS/CEIC3NSzsrmBVSGLQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:KHg34Q==,iv:4KCcoUor2St0LikEPnWYTQ5vFlkoDu3v/2WmBO93WnM=,tag:UmXuZJid/yN3MnQT62eG2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWlNZSVFwamNYdjE1QnJm
            QW5ubVlack9KUW5RMTM4QUx3dlhacllQUERVCmJiWmJKSURxc1M0NGdBK2hYd1JW
            Vkp1eFh2RjRBZW9MZUM0R3NUU1FFaFEKLS0tIDk4NGFKVys2VXpFY05VTEJLRFJW
            V0R6RGtQQmRRWmFQak9oVm5HSEkwUWsK7upriYVkbRWIO0Ezbigj5vnMmnrUk91T
            11jpQIiik0AxvgmKvGpHDzuTihOE/3RWrGYbaxPFblubp/jGsGLsKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pr5g055yvw9e7q7nczde5zm7phhktjr9prrf2swgnrg8q3t7myjqdzng4a
    lastmodified: "2026-08-08T09:57:36Z"
    mac: ENC[AES256_GCM,data:j2ovHy5wlsIBgLEm5ecGf+4KoNOOwPOAtIqDY7wd+owRLkYQ/T6VOiYnG6IXb5XeKlwwJ5X0IFiwBKfbilL2NmSdPlWErHuu3PQ6rFruSnP0ZQW24VJAxixnIk7FO3lmkvSUM4NKpQE6Rzbj1vYjbg2b4seuba7LrXS5svcjnDk=,iv:cjePCJWtTolD68UFPmM//NpZ7ABm3GChvgcicmseKB8=,tag:5Tn6TkMKY+FDbhMV1PlHbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
