secret:
    dbUser: ENC[AES256_GCM,data:t/Ifkw==,iv:MOgexj9r2Yh9u38YOy7gFMOrFrA5xg+tAOHImKj9Ha0=,tag:2x6Hy/g7KCE32RhCou3PVA==,type:str]
    dbPassword: ENC[AES256_GCM,data:Qpp/tw==,iv:UxJM9KJwBk2M10OeYl/6SbSoWYR3doB7qz0sJGzLt3c=,tag:TL20DEbIpVrB0b7456QV7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WjVoaHJjbnhrcmtySFkw
            YjFZVTVKMm9nVWVRWFpPMXJGL0hFVmRVV2hrCjBWalYvMG9KZzNpRlNNeHo1L25u
            OGZLcGluRlp1VmMvZktXNDU0U0VLcmMKLS0tIFlBTnRsaHoxeHA3TjViMTVTcnVR
            MTB4dURLc3ZQdkhSNXBiOWZ0K1ZWWmMKb1jzDtFJIaN9f80+79zXm54Z4AIo+52H
            i1Fm9jThuwXPW35IQNruWRbuwZzgwrT6B507iDqg4NFBRpU/SyzO7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pr5g055yvw9e7q7nczde5zm7phhktjr9prrf2swgnrg8q3t7myjqdzng4a
    lastmodified: "2026-08-08T09:57:26Z"
    mac: ENC[AES256_GCM,data:925f7OV9hhWIzpGAfdKyqdkeVg4zkhm8rDMxjabxB0xZGCrImC/R7wgFwjV/I60OK7CH2Y2ZRDe+sr5p2tXM81R8eO6stzKdNYGqfid3Hwo/dBniQ9Bu+0Fa7brEcXEioYpUWwJP2gwEUFGSxWg7UUt065s+JeF73SB7XPjfzQw=,iv:7AI+HIFKrxSqOeZ+3F9jAkAgBBE7hSmqZ4zE7AJEC+w=,tag:bLqLBCnZpmgwpuJM+pdqDw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
